// src/domain/entities/User.ts
export enum UserRole {
  TOURIST = 'tourist',
  PROVIDER = 'provider',
  ADMIN = 'admin'
}

export interface User {
  id: string;
  name: string;
  email: string;
  passwordHash: string;
  role: UserRole;
  phone?: string;
  isVerified: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export class UserEntity implements User {
  constructor(
    public id: string,
    public name: string,
    public email: string,
    public passwordHash: string,
    public role: UserRole,
    public isVerified: boolean = false,
    public phone?: string,
    public createdAt: Date = new Date(),
    public updatedAt: Date = new Date()
  ) {}

  static create(name: string, email: string, passwordHash: string, role: UserRole, phone?: string): UserEntity {
    return new UserEntity(
      '', // ID will be generated by MongoDB
      name,
      email,
      passwordHash,
      role,
      false,
      phone
    );
  }
}